# Generated by Django 4.0.2 on 2022-03-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phno', models.IntegerField(max_length=12)),
                ('uname', models.CharField(max_length=20)),
                ('pswd', models.CharField(max_length=20)),
                ('cpswd', models.CharField(max_length=20)),
            ],
        ),
    ]
