# Generated by Django 4.0.2 on 2022-03-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=100)),
                ('sub_date', models.CharField(max_length=25)),
            ],
        ),
    ]
