# Generated by Django 4.0.2 on 2022-03-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=50)),
                ('material', models.FileField(upload_to='')),
            ],
        ),
    ]
