# Generated by Django 4.0.2 on 2022-03-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_exams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=105)),
                ('photo', models.FileField(upload_to='')),
                ('descr', models.CharField(max_length=700)),
            ],
        ),
    ]
